import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Drift from "react-driftjs";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Drift Integration!</a>
                </h1>
            </main>
            <Drift
                appId="zkzk8k7497g8"
                userId="1234"
                attributes={{email: "user@example.com", company: "Acme Inc"}}
            />
        </div>
    )
}
