import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useIntercom} from "react-use-intercom";
import {useEffect} from "react";
import { IntercomProvider } from 'react-use-intercom';

const INTERCOM_APP_ID = 'uld0qzrb';

export default function Home() {
    const {boot} = useIntercom();

    useEffect(() => {
        // Update the document title using the browser API
        boot({
            name: 'Russo',
            userId: '1234',
            customAttributes: {custom_attribute_key: 'hi there'},
        })
    });

    return (
        <IntercomProvider appId={INTERCOM_APP_ID}>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className={styles.main}>
                    <h1 className={styles.title}>
                        Welcome to <a href="https://nextjs.org">Intercom Integration!</a>
                    </h1>
                </main>
            </div>
        </IntercomProvider>
    )
}
