import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useZafClient} from "../utils/zafClient";

export default function Home() {
    useZafClient('identify', {
        name: 'Jagadesh',
        email: 'jagadesh@test.com',
        organization: 'Test, Inc.'
    });
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Zendesk Integration!</a>
                </h1>
            </main>
            <div id="ze-snippet">
            </div>
        </div>
    )
}
